version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/ASP.Net Mvc Core UI Composition"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/ASP.Net Core API Gateway - 02"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/ASP.Net Core API Gateway - 01"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/ASP.Net Mvc Core"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
