version: '{build}'
image: Visual Studio 2022

skip_branch_with_pr: true
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

test: off
deploy: off

branches:
  only:
    - master

build_script:
  - cmd: ./build.cmd
  